name: Terraform PR Validation

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - develop
      - feature/**

jobs:

  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.1

      - name: Terraform Version
        run: terraform version

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate